/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package process_disk_scheduling;

import javax.swing.JOptionPane;

/**
 *
 * @author Yogi
 */
public class select_process_algo extends javax.swing.JFrame {

    /**
     * Creates new form select_process_algo
     */
    public select_process_algo() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        ok = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        close = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fcfsProcess = new javax.swing.JRadioButton();
        hrnnProcess = new javax.swing.JRadioButton();
        sjfProcess = new javax.swing.JRadioButton();
        ljfProcess = new javax.swing.JRadioButton();
        rrobin = new javax.swing.JRadioButton();
        lrtf = new javax.swing.JRadioButton();
        srtf = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(null);

        ok.setBackground(new java.awt.Color(0, 0, 0));
        ok.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ok.setForeground(new java.awt.Color(255, 255, 255));
        ok.setText("ALGORITHM");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        jPanel1.add(ok);
        ok.setBounds(470, 390, 120, 30);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("THEORY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(350, 390, 100, 30);

        close.setBackground(new java.awt.Color(0, 0, 0));
        close.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setText("CLOSE");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        jPanel1.add(close);
        close.setBounds(610, 390, 90, 30);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 3, 29)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PROCESS SCHEDULING ALGORITHMS");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 20, 580, 41);

        fcfsProcess.setBackground(new java.awt.Color(16, 191, 191));
        buttonGroup1.add(fcfsProcess);
        fcfsProcess.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        fcfsProcess.setForeground(new java.awt.Color(255, 255, 255));
        fcfsProcess.setText("FCFS Algorithm");
        fcfsProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fcfsProcessActionPerformed(evt);
            }
        });
        jPanel1.add(fcfsProcess);
        fcfsProcess.setBounds(50, 70, 230, 31);

        hrnnProcess.setBackground(new java.awt.Color(16, 191, 191));
        buttonGroup1.add(hrnnProcess);
        hrnnProcess.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        hrnnProcess.setForeground(new java.awt.Color(255, 255, 255));
        hrnnProcess.setText("HRRN Algorithm");
        hrnnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hrnnProcessActionPerformed(evt);
            }
        });
        jPanel1.add(hrnnProcess);
        hrnnProcess.setBounds(50, 220, 230, 31);

        sjfProcess.setBackground(new java.awt.Color(16, 191, 191));
        buttonGroup1.add(sjfProcess);
        sjfProcess.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sjfProcess.setForeground(new java.awt.Color(255, 255, 255));
        sjfProcess.setText("SJF Algorithm");
        sjfProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sjfProcessActionPerformed(evt);
            }
        });
        jPanel1.add(sjfProcess);
        sjfProcess.setBounds(50, 120, 230, 31);

        ljfProcess.setBackground(new java.awt.Color(16, 191, 191));
        buttonGroup1.add(ljfProcess);
        ljfProcess.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ljfProcess.setForeground(new java.awt.Color(255, 255, 255));
        ljfProcess.setText("LJF Algorithm");
        ljfProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ljfProcessActionPerformed(evt);
            }
        });
        jPanel1.add(ljfProcess);
        ljfProcess.setBounds(50, 170, 230, 31);

        rrobin.setBackground(new java.awt.Color(16, 191, 191));
        buttonGroup1.add(rrobin);
        rrobin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rrobin.setForeground(new java.awt.Color(255, 255, 255));
        rrobin.setText("Round Robin Algorithm");
        rrobin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rrobinActionPerformed(evt);
            }
        });
        jPanel1.add(rrobin);
        rrobin.setBounds(50, 270, 260, 31);

        lrtf.setBackground(new java.awt.Color(16, 191, 191));
        buttonGroup1.add(lrtf);
        lrtf.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lrtf.setForeground(new java.awt.Color(255, 255, 255));
        lrtf.setText("LRTF Algorithm");
        lrtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lrtfActionPerformed(evt);
            }
        });
        jPanel1.add(lrtf);
        lrtf.setBounds(50, 320, 230, 31);

        srtf.setBackground(new java.awt.Color(16, 191, 191));
        buttonGroup1.add(srtf);
        srtf.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        srtf.setForeground(new java.awt.Color(255, 255, 255));
        srtf.setText("SRTF Algorithm");
        srtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srtfActionPerformed(evt);
            }
        });
        jPanel1.add(srtf);
        srtf.setBounds(50, 370, 230, 31);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/process_disk_scheduling/abstract-art-atom-background.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(-30, 0, 750, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        // TODO add your handling code here:
        if (fcfsProcess.isSelected()) {
            fcfs_process algo = new fcfs_process();
            algo.show();
        }
        else if (sjfProcess.isSelected()) {
            sjf_process algo = new sjf_process();
            algo.show();
        }
        else if (ljfProcess.isSelected()) {
            ljf_process algo = new ljf_process();
            algo.show();
        }
        else if (hrnnProcess.isSelected()) {
            hrnn_process algo = new hrnn_process();
            algo.show();
        }
        else if (rrobin.isSelected()) {
            roundrobin_process algo = new roundrobin_process();
            algo.show();
        }
        else if (lrtf.isSelected()) {
            lrtf_process algo = new lrtf_process();
            algo.show();
        }
        else if (srtf.isSelected()) {
            srtf_process algo = new srtf_process();
            algo.show();
        }
        else {
            JOptionPane.showMessageDialog(this,"Select a Process Scheduling Algorithm.");
        }
    }//GEN-LAST:event_okActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_closeActionPerformed

    private void fcfsProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fcfsProcessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fcfsProcessActionPerformed

    private void hrnnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrnnProcessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrnnProcessActionPerformed

    private void sjfProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sjfProcessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sjfProcessActionPerformed

    private void ljfProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ljfProcessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ljfProcessActionPerformed

    private void rrobinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rrobinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rrobinActionPerformed

    private void lrtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lrtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lrtfActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (fcfsProcess.isSelected()) {
            fcfs_info algo = new fcfs_info();
            algo.show();
        }
        else if (sjfProcess.isSelected()) {
            sjf_info algo = new sjf_info();
            algo.show();
        }
        else if (ljfProcess.isSelected()) {
            ljf_info algo = new ljf_info();
            algo.show();
        }
        else if (hrnnProcess.isSelected()) {
            hrnn_info algo = new hrnn_info();
            algo.show();
        }
        else if (rrobin.isSelected()) {
            round_info algo = new round_info();
            algo.show();
        }
        else if (lrtf.isSelected()) {
            lrtf_info algo = new lrtf_info();
            algo.show();
        }
        else if (srtf.isSelected()) {
            srtf_info algo = new srtf_info();
            algo.show();
        }
        else {
            JOptionPane.showMessageDialog(this,"Select a Process Scheduling Algorithm.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void srtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_srtfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(select_process_algo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(select_process_algo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(select_process_algo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(select_process_algo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new select_process_algo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton close;
    private javax.swing.JRadioButton fcfsProcess;
    private javax.swing.JRadioButton hrnnProcess;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton ljfProcess;
    private javax.swing.JRadioButton lrtf;
    private javax.swing.JButton ok;
    private javax.swing.JRadioButton rrobin;
    private javax.swing.JRadioButton sjfProcess;
    private javax.swing.JRadioButton srtf;
    // End of variables declaration//GEN-END:variables
}
