/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package process_disk_scheduling;

import javax.swing.JOptionPane;

/**
 *
 * @author Sanskar Bhuwania
 */
public class select_algo extends javax.swing.JFrame {
    /**
     * Creates new form select_alg
     */
    public select_algo() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        fcfs = new javax.swing.JRadioButton();
        sstf = new javax.swing.JRadioButton();
        scan = new javax.swing.JRadioButton();
        c_scan = new javax.swing.JRadioButton();
        look = new javax.swing.JRadioButton();
        c_look = new javax.swing.JRadioButton();
        ok = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 15));
        jPanel1.setLayout(null);

        fcfs.setBackground(new java.awt.Color(16, 191, 191));
        buttonGroup1.add(fcfs);
        fcfs.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        fcfs.setForeground(new java.awt.Color(255, 255, 255));
        fcfs.setText("FCFS algorithm");
        fcfs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fcfsActionPerformed(evt);
            }
        });
        jPanel1.add(fcfs);
        fcfs.setBounds(67, 93, 160, 29);

        sstf.setBackground(new java.awt.Color(16, 191, 191));
        buttonGroup1.add(sstf);
        sstf.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        sstf.setForeground(new java.awt.Color(255, 255, 255));
        sstf.setText("SSTF algorithm");
        sstf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sstfActionPerformed(evt);
            }
        });
        jPanel1.add(sstf);
        sstf.setBounds(67, 140, 160, 29);

        scan.setBackground(new java.awt.Color(16, 191, 191));
        buttonGroup1.add(scan);
        scan.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        scan.setForeground(new java.awt.Color(255, 255, 255));
        scan.setText("SCAN algorithm");
        scan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scanActionPerformed(evt);
            }
        });
        jPanel1.add(scan);
        scan.setBounds(67, 187, 160, 29);

        c_scan.setBackground(new java.awt.Color(16, 191, 191));
        buttonGroup1.add(c_scan);
        c_scan.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        c_scan.setForeground(new java.awt.Color(255, 255, 255));
        c_scan.setText("C-SCAN algorithm");
        c_scan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_scanActionPerformed(evt);
            }
        });
        jPanel1.add(c_scan);
        c_scan.setBounds(67, 234, 160, 29);

        look.setBackground(new java.awt.Color(16, 191, 191));
        buttonGroup1.add(look);
        look.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        look.setForeground(new java.awt.Color(255, 255, 255));
        look.setText("LOOK algorithm");
        look.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lookActionPerformed(evt);
            }
        });
        jPanel1.add(look);
        look.setBounds(67, 281, 160, 29);

        c_look.setBackground(new java.awt.Color(16, 191, 191));
        buttonGroup1.add(c_look);
        c_look.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        c_look.setForeground(new java.awt.Color(255, 255, 255));
        c_look.setText("C-LOOK algorithm");
        c_look.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_lookActionPerformed(evt);
            }
        });
        jPanel1.add(c_look);
        c_look.setBounds(67, 328, 160, 29);

        ok.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        jPanel1.add(ok);
        ok.setBounds(510, 380, 73, 29);

        exit.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        exit.setText("Close");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit);
        exit.setBounds(610, 380, 73, 29);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 3, 29)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DISK SCHEDULING ALGORITHMS");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(100, 20, 500, 41);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void sstfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sstfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sstfActionPerformed

    private void scanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scanActionPerformed

    private void c_scanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_scanActionPerformed
        // TODO add your handling code here: 
    }//GEN-LAST:event_c_scanActionPerformed

    private void fcfsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fcfsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fcfsActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        // TODO add your handling code here:      
        if (fcfs.isSelected()) {
            fcfs algo = new fcfs();
            algo.show();
        }
        else if (sstf.isSelected()) {
            sstf algo = new sstf();
            algo.show();
        }
        else if (scan.isSelected()) {
            scan algo = new scan();
            algo.show();
        }
        else if (c_scan.isSelected()) {
            c_scan algo = new c_scan();
            algo.show();
        }
        else if (look.isSelected()) {
            look algo = new look();
            algo.show();
        }
        else if (c_look.isSelected()) {
            c_look algo = new c_look();
            algo.show();
        }
        else {
            JOptionPane.showMessageDialog(this,"Select a Disk Scheduling Algorithm.");
        }
    }//GEN-LAST:event_okActionPerformed

    private void lookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lookActionPerformed

    private void c_lookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_lookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_lookActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(select_algo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(select_algo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(select_algo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(select_algo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new select_algo().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton c_look;
    private javax.swing.JRadioButton c_scan;
    private javax.swing.JButton exit;
    private javax.swing.JRadioButton fcfs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton look;
    private javax.swing.JButton ok;
    private javax.swing.JRadioButton scan;
    private javax.swing.JRadioButton sstf;
    // End of variables declaration//GEN-END:variables
}
